### ISSUE TITLE
Is this program can be portable?

### ISSUE THREAD

**Issue by Stamimail** [stefankueng/TrafficWatcher#1]
The current version requires WinPCap installation.

**Comment by stefankueng** [comment]
You've answered yourself: WinPCap is required. And WinPCap requires installation (it's a driver).
So no, there won't be a portable version ever.

**Comment by Stamimail** [comment]
I meant to import the relevant compeonent of WinPCap to TrafficWatcher.
So I understand that the relevant compeonent it's actually a driver, and that drivers can't be used without an installtion?

**Comment by stefankueng** [comment]
yes, a driver requires installation.
